# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-01 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippetsapp', '0002_snippet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='highlight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
